import os

ENV_NAMESPACE = os.environ.get("ENV_KEYS_NAMESPACE", "POLYAXON")

# Platform
ENV_KEYS_PLATFORM_CONFIG = "{}_PLATFORM_CONFIG".format(ENV_NAMESPACE)

# Context path for Polyaxon's config files
ENV_KEYS_HOME = "{}_HOME".format(ENV_NAMESPACE)

# General
ENV_KEYS_NO_CONFIG = "{}_NO_CONFIG".format(ENV_NAMESPACE)
ENV_KEYS_SERVICE = "{}_SERVICE".format(ENV_NAMESPACE)
ENV_KEYS_ENVIRONMENT = "{}_ENVIRONMENT".format(ENV_NAMESPACE)
ENV_KEYS_HEADER = "{}_HEADER".format(ENV_NAMESPACE)
ENV_KEYS_HEADER_SERVICE = "{}_HEADER_SERVICE".format(ENV_NAMESPACE)
ENV_KEYS_AUTHENTICATION_TYPE = "{}_AUTHENTICATION_TYPE".format(ENV_NAMESPACE)
ENV_KEYS_DEBUG = "{}_DEBUG".format(ENV_NAMESPACE)
ENV_KEYS_TIMEOUT = "{}_TIMEOUT".format(ENV_NAMESPACE)
ENV_KEYS_TRACKING_TIMEOUT = "{}_TRACKING_TIMEOUT".format(ENV_NAMESPACE)
ENV_KEYS_TIME_ZONE = "{}_TIME_ZONE".format(ENV_NAMESPACE)
ENV_KEYS_WATCH_INTERVAL = "{}_WATCH_INTERVAL".format(ENV_NAMESPACE)
ENV_KEYS_INTERVAL = "{}_INTERVAL".format(ENV_NAMESPACE)
ENV_KEYS_LOG_LEVEL = "{}_LOG_LEVEL".format(ENV_NAMESPACE)
ENV_KEYS_K8S_NAMESPACE = "{}_K8S_NAMESPACE".format(ENV_NAMESPACE)
ENV_KEYS_K8S_NODE_NAME = "{}_K8S_NODE_NAME".format(ENV_NAMESPACE)
ENV_KEYS_K8S_POD_ID = "{}_K8S_POD_ID".format(ENV_NAMESPACE)
ENV_KEYS_PLATFORM_HOST = "{}_PLATFORM_HOST".format(ENV_NAMESPACE)
ENV_KEYS_HOST = "{}_HOST".format(ENV_NAMESPACE)
ENV_KEYS_API_VERSION = "{}_API_VERSION".format(ENV_NAMESPACE)
ENV_KEYS_VERIFY_SSL = "{}_VERIFY_SSL".format(ENV_NAMESPACE)
ENV_KEYS_SSL_CA_CERT = "{}_SSL_CA_CERT".format(ENV_NAMESPACE)
ENV_KEYS_CERT_FILE = "{}_CERT_FILE".format(ENV_NAMESPACE)
ENV_KEYS_KEY_FILE = "{}_KEY_FILE".format(ENV_NAMESPACE)
ENV_KEYS_ASSERT_HOSTNAME = "{}_ASSERT_HOSTNAME".format(ENV_NAMESPACE)
ENV_KEYS_CONNECTION_POOL_MAXSIZE = "{}_CONNECTION_POOL_MAXSIZE".format(ENV_NAMESPACE)
ENV_KEYS_LOGS_ROOT = "{}_LOG_ROOT".format(ENV_NAMESPACE)
ENV_KEYS_ARCHIVES_ROOT = "{}_ARCHIVES_ROOT".format(ENV_NAMESPACE)
ENV_KEYS_ARTIFACTS_ROOT = "{}_ARTIFACTS_ROOT".format(ENV_NAMESPACE)
ENV_KEYS_STATIC_ROOT = "{}_STATIC_ROOT".format(ENV_NAMESPACE)
ENV_KEYS_CONTEXT_ROOT = "{}_CONTEXT_ROOT".format(ENV_NAMESPACE)
ENV_KEYS_OFFLINE_ROOT = "{}_OFFLINE_ROOT".format(ENV_NAMESPACE)
ENV_KEYS_DISABLE_ERRORS_REPORTING = "{}_DISABLE_ERRORS_REPORTING".format(ENV_NAMESPACE)
ENV_KEYS_INTERVALS_COMPATIBILITY_CHECK = "{}_INTERVALS_COMPATIBILITY_CHECK".format(
    ENV_NAMESPACE
)
ENV_KEYS_RETRIES = "{}_RETRIES".format(ENV_NAMESPACE)
ENV_KEYS_UPLOAD_SIZE = "{}_UPLOAD_SIZE".format(ENV_NAMESPACE)
ENV_KEYS_MAX_CONCURRENCY = "{}_MAX_CONCURRENCY".format(ENV_NAMESPACE)
ENV_KEYS_HAS_PROCESS_SIDECAR = "{}_HAS_PROCESS_SIDECAR".format(ENV_NAMESPACE)

# Secrets
ENV_KEYS_SECRET_KEY = "{}_SECRET_KEY".format(ENV_NAMESPACE)  # noqa
ENV_KEYS_SECRET_INTERNAL_TOKEN = "{}_SECRET_INTERNAL_TOKEN".format(
    ENV_NAMESPACE
)  # noqa
ENV_KEYS_AUTH_TOKEN = "{}_AUTH_TOKEN".format(ENV_NAMESPACE)
ENV_KEYS_AUTH_USERNAME = "{}_AUTH_USERNAME".format(ENV_NAMESPACE)
ENV_KEYS_CUSTOM_ERRORS_OPTIONS = "{}_CUSTOM_ERRORS_OPTIONS".format(ENV_NAMESPACE)

# Containers
ENV_KEYS_AGENT_INSTANCE = "{}_AGENT_INSTANCE".format(ENV_NAMESPACE)
ENV_KEYS_RUN_INSTANCE = "{}_RUN_INSTANCE".format(ENV_NAMESPACE)
ENV_KEYS_CONTAINER_ID = "{}_CONTAINER_ID".format(ENV_NAMESPACE)
ENV_KEYS_HASH_LENGTH = "{}_HASH_LENGTH".format(ENV_NAMESPACE)

# Flags
ENV_KEYS_K8S_IN_CLUSTER = "{}_K8S_IN_CLUSTER".format(ENV_NAMESPACE)
ENV_KEYS_IS_MANAGED = "{}_IS_MANAGED".format(ENV_NAMESPACE)
ENV_KEYS_IS_OFFLINE = "{}_IS_OFFLINE".format(ENV_NAMESPACE)
ENV_KEYS_NO_OP = "{}_NO_OP".format(ENV_NAMESPACE)
ENV_KEYS_NO_API = "{}_NO_API".format(ENV_NAMESPACE)

# Registry
ENV_KEYS_USE_GIT_REGISTRY = "{}_USE_GIT_REGISTRY".format(ENV_NAMESPACE)
ENV_KEYS_PUBLIC_REGISTRY = "{}_PUBLIC_REGISTRY".format(ENV_NAMESPACE)

# Agent
ENV_KEYS_AGENT_SIDECAR = "{}_AGENT_SIDECAR".format(ENV_NAMESPACE)
ENV_KEYS_AGENT_INIT = "{}_AGENT_INIT".format(ENV_NAMESPACE)
ENV_KEYS_AGENT_CLEANER = "{}_AGENT_CLEANER".format(ENV_NAMESPACE)
ENV_KEYS_AGENT_NOTIFIER = "{}_AGENT_NOTIFIER".format(ENV_NAMESPACE)
ENV_KEYS_AGENT_DEFAULT_SCHEDULING = "{}_AGENT_DEFAULT_SCHEDULING".format(ENV_NAMESPACE)
ENV_KEYS_AGENT_DEFAULT_IMAGE_PULL_SECRETS = (
    "{}_AGENT_DEFAULT_IMAGE_PULL_SECRETS".format(ENV_NAMESPACE)
)
ENV_KEYS_AGENT_ARTIFACTS_STORE = "{}_AGENT_ARTIFACTS_STORE".format(ENV_NAMESPACE)
ENV_KEYS_AGENT_CONNECTIONS = "{}_AGENT_CONNECTIONS".format(ENV_NAMESPACE)
ENV_KEYS_SET_AGENT = "{}_SET_AGENT".format(ENV_NAMESPACE)
ENV_KEYS_K8S_APP_SECRET_NAME = "{}_K8S_APP_SECRET_NAME".format(ENV_NAMESPACE)  # noqa
ENV_KEYS_AGENT_SECRET_NAME = "{}_AGENT_SECRET_NAME".format(ENV_NAMESPACE)  # noqa
ENV_KEYS_AGENT_RUNS_SA = "{}_AGENT_RUNS_SA".format(ENV_NAMESPACE)
ENV_KEYS_AGENT_ENABLE_HEALTH_CHECKS = "{}_AGENT_ENABLE_HEALTH_CHECKS".format(
    ENV_NAMESPACE
)
ENV_KEYS_AGENT_EXECUTOR_REFRESH_INTERVAL = "{}_AGENT_EXECUTOR_REFRESH_INTERVAL".format(
    ENV_NAMESPACE
)
ENV_KEYS_AGENT_IS_REPLICA = "{}_AGENT_IS_REPLICA".format(ENV_NAMESPACE)
ENV_KEYS_AGENT_USE_PROXY_ENV_VARS_IN_OPS = "{}_AGENT_USE_PROXY_ENV_VARS_IN_OPS".format(
    ENV_NAMESPACE
)

# Connections
ENV_KEYS_COLLECT_ARTIFACTS = "{}_COLLECT_ARTIFACTS".format(ENV_NAMESPACE)
ENV_KEYS_COLLECT_RESOURCES = "{}_COLLECT_RESOURCES".format(ENV_NAMESPACE)
ENV_KEYS_ARTIFACTS_STORE_NAME = "{}_ARTIFACTS_STORE_NAME".format(ENV_NAMESPACE)
ENV_KEYS_GIT_CREDENTIALS = "{}_GIT_CREDENTIALS".format(ENV_NAMESPACE)
ENV_KEYS_GIT_CREDENTIALS_STORE = "{}_GIT_CREDENTIALS_STORE".format(ENV_NAMESPACE)
ENV_KEYS_SSH_PATH = "{}_SSH_PATH".format(ENV_NAMESPACE)
ENV_KEYS_SSH_PRIVATE_KEY = "{}_SSH_PRIVATE_KEY".format(ENV_NAMESPACE)

# Ops
ENV_KEYS_ISTIO_ENABLED = "{}_ISTIO_ENABLED".format(ENV_NAMESPACE)
ENV_KEYS_TFJOB_ENABLED = "{}_TFJOB_ENABLED".format(ENV_NAMESPACE)
ENV_KEYS_PYTORCH_JOB_ENABLED = "{}_PYTORCH_JOB_ENABLED".format(ENV_NAMESPACE)
ENV_KEYS_PADDLE_JOB_ENABLED = "{}_PADDLE_JOB_ENABLED".format(ENV_NAMESPACE)
ENV_KEYS_MXJOB_ENABLED = "{}_MXJOB_ENABLED".format(ENV_NAMESPACE)
ENV_KEYS_XGBOOST_JOB_ENABLED = "{}_XGBOOST_JOB_ENABLED".format(ENV_NAMESPACE)
ENV_KEYS_MPIJOB_ENABLED = "{}_MPIJOB_ENABLED".format(ENV_NAMESPACE)
ENV_KEYS_RAYJOB_ENABLED = "{}_RAYJOB_ENABLED".format(ENV_NAMESPACE)
ENV_KEYS_DASKJOB_ENABLED = "{}_DASKJOB_ENABLED".format(ENV_NAMESPACE)

# Sandbox
ENV_KEYS_SANDBOX_PORT = "{}_SANDBOX_PORT".format(ENV_NAMESPACE)
ENV_KEYS_SANDBOX_HOST = "{}_SANDBOX_HOST".format(ENV_NAMESPACE)
ENV_KEYS_SANDBOX_DEBUG = "{}_SANDBOX_DEBUG".format(ENV_NAMESPACE)
ENV_KEYS_SANDBOX_SSL_ENABLED = "{}_SANDBOX_SSL_ENABLED".format(ENV_NAMESPACE)
ENV_KEYS_SANDBOX_WORKERS = "{}_SANDBOX_WORKERS".format(ENV_NAMESPACE)
ENV_KEYS_SANDBOX_PER_CORE = "{}_SANDBOX_PER_CORE".format(ENV_NAMESPACE)
ENV_KEYS_SANDBOX_IS_LOCAL = "{}_SANDBOX_IS_LOCAL".format(ENV_NAMESPACE)
ENV_KEYS_SANDBOX_ROOT = "{}_SANDBOX_ROOT".format(ENV_NAMESPACE)

# Proxies
ENV_KEYS_PROXY_NAMESPACES = "{}_PROXY_NAMESPACES".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_GATEWAY_PORT = "{}_PROXY_GATEWAY_PORT".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_GATEWAY_TARGET_PORT = "{}_PROXY_GATEWAY_TARGET_PORT".format(
    ENV_NAMESPACE
)
ENV_KEYS_PROXY_GATEWAY_HOST = "{}_PROXY_GATEWAY_HOST".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_STREAMS_PORT = "{}_PROXY_STREAMS_PORT".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_STREAMS_TARGET_PORT = "{}_PROXY_STREAMS_TARGET_PORT".format(
    ENV_NAMESPACE
)
ENV_KEYS_PROXY_STREAMS_HOST = "{}_PROXY_STREAMS_HOST".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_API_PORT = "{}_PROXY_API_PORT".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_API_TARGET_PORT = "{}_PROXY_API_TARGET_PORT".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_API_HOST = "{}_PROXY_API_HOST".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_LOCAL_PORT = "{}_PROXY_LOCAL_PORT".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_API_USE_RESOLVER = "{}_PROXY_API_USE_RESOLVER".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_SSL_PATH = "{}_PROXY_SSL_PATH".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_SSL_ENABLED = "{}_PROXY_SSL_ENABLED".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_AUTH_ENABLED = "{}_PROXY_AUTH_ENABLED".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_AUTH_EXTERNAL = "{}_PROXY_AUTH_EXTERNAL".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_AUTH_USE_RESOLVER = "{}_PROXY_AUTH_USE_RESOLVER".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_HAS_FORWARD_PROXY = "{}_PROXY_HAS_FORWARD_PROXY".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_FORWARD_PROXY_PORT = "{}_PROXY_FORWARD_PROXY_PORT".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_FORWARD_PROXY_HOST = "{}_PROXY_FORWARD_PROXY_HOST".format(ENV_NAMESPACE)
ENV_KEYS_PROXY_FORWARD_PROXY_KIND = "{}_PROXY_FORWARD_PROXY_KIND".format(ENV_NAMESPACE)
ENV_KEYS_UI_IN_SANDBOX = "{}_UI_IN_SANDBOX".format(ENV_NAMESPACE)
ENV_KEYS_UI_ADMIN_ENABLED = "{}_UI_ADMIN_ENABLED".format(ENV_NAMESPACE)
ENV_KEYS_UI_ASSETS_VERSION = "{}_UI_ASSETS_VERSION".format(ENV_NAMESPACE)
ENV_KEYS_UI_ENABLED = "{}_UI_ENABLED".format(ENV_NAMESPACE)
ENV_KEYS_UI_OFFLINE = "{}_UI_OFFLINE".format(ENV_NAMESPACE)
ENV_KEYS_UI_BASE_URL = "{}_UI_BASE_URL".format(ENV_NAMESPACE)
ENV_KEYS_STATIC_URL = "{}_STATIC_URL".format(ENV_NAMESPACE)
ENV_KEYS_DNS_USE_RESOLVER = "{}_DNS_USE_RESOLVER".format(ENV_NAMESPACE)
ENV_KEYS_DNS_CUSTOM_CLUSTER = "{}_DNS_CUSTOM_CLUSTER".format(ENV_NAMESPACE)
ENV_KEYS_DNS_BACKEND = "{}_DNS_BACKEND".format(ENV_NAMESPACE)
ENV_KEYS_DNS_PREFIX = "{}_DNS_PREFIX".format(ENV_NAMESPACE)
ENV_KEYS_NGINX_TIMEOUT = "{}_NGINX_TIMEOUT".format(ENV_NAMESPACE)
ENV_KEYS_NGINX_INDENT_CHAR = "{}_NGINX_INDENT_CHAR".format(ENV_NAMESPACE)
ENV_KEYS_NGINX_INDENT_WIDTH = "{}_NGINX_INDENT_WIDTH".format(ENV_NAMESPACE)
